### ISSUE TITLE
With 0.5.8 on Kindle PW2 ver 5.6.1 pdf files still open with kindle default pdf viewer

### ISSUE THREAD

**Issue by stbinan** [koreader/kpvbooklet#15]

**Comment by viteo** [comment]
i like default pdf viewer, how can i get it back and safe other kpvbooklet functions?

**Comment by chrox** [comment]
@stbinan I cannot reproduce this on neither 5.6.1 or 5.6.2. If you still have this problem, you can try uninstall and reinstall it with the latest kpvbooklet release. Good luck.

**Comment by chrox** [comment]
@viteo You can long hold the PDF document item in the home screen and in the popup menu select "Goto..." to open the PDF with native reader. 

But started from 5.6.2 this won't work for file names that contain spaces. It's probably a bug in the native system because even I uninstall the kpvbooklet the native system still cannot open PDF documents that have spaces in the filenames. The native reader tries to open file path that contains "%20" escape.
